<?php
/**
 * @file
 * Contains \Drupal\statzconvert\wsCSVForm
 */

namespace Drupal\statzconvert\Form;

use Drupal\Core\Database;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class wsCSVForm
 * @package Drupal\statzconvert\Form
 */
class wsCSVForm extends FormBase {
    public function getFormId() {
        return 'wscsv_form';
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(array $form, FormStateInterface $form_state)
    {
        $nid = \Drupal::routeMatch()->getRawParameter('node');

        $form['chkempty4v'] = [
            '#type' => 'checkbox',
            '#title' => $this->t('Use Empty Dummy Team for Visitors'),
        ];

        $form['dbvteam'] = [
            '#type' => 'select',
            '#title' => 'Visitor Team (FoxBox)',
            '#options' => [
                '' => $this->t('Please Select...'),
                'BU' => 'BAYLOR',
            ],
            '#required' => TRUE,
        ];

        $form['dbhteam'] = [
            '#type' => 'select',
            '#title' => 'Home Team (FoxBox)',
            '#options' => [
                '' => $this->t('Please Select...'),
                'BU' => 'BAYLOR',
            ],
            '#required' => TRUE,
        ];

        $form['vteamid'] = [
            '#type' => 'textfield',
            '#title' => $this->t('Visitor Team ID'),
            '#required' => TRUE,
        ];

        $form['hteamid'] = [
            '#type' => 'textfield',
            '#title' => $this->t('Home Team ID'),
            '#required' => TRUE,
        ];

        $form['filvteamros'] = [
            '#type' => 'file',
            '#title' => t('Visitor Roster CSV File'),
        ];

        $form['filhteamros'] = [
            '#type' => 'file',
            '#title' => t('Home Roster CSV File'),
        ];

        $form['submit'] = [
            '#type' => 'submit',
            '#value' => $this->t('Convert'),
        ];

        $form['nid'] = [
            '#type' => 'hidden',
            '#value' => $nid,
        ];

        //$form['#theme'] = 'scxmlutils';

        return $form;
    }

    /**
     * {@inheritdoc}
     */
    public function validateForm(array &$form, FormStateInterface $form_state)
    {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        // TODO: Implement submitForm() method.
    }
}